"""Generate memorable passphrases for learner authentication.

Uses a curated wordlist of common, kid-friendly English words.
4 words from ~2000 gives ~44 bits of entropy — sufficient for a POC
where accounts are teacher-managed.
"""

from __future__ import annotations

import secrets

# fmt: off
_WORDS: tuple[str, ...] = (
    "apple", "arrow", "badge", "baker", "beach", "bear", "bird", "blade",
    "blank", "blaze", "block", "bloom", "board", "bonus", "book", "booth",
    "brave", "brick", "bridge", "brief", "bright", "broad", "brook", "brush",
    "build", "bunch", "burst", "cabin", "calm", "camp", "candy", "cape",
    "cargo", "carry", "catch", "chain", "chalk", "chase", "chess", "chief",
    "chill", "chirp", "class", "clean", "clear", "cliff", "climb", "clock",
    "close", "cloud", "clown", "coach", "coast", "color", "comet", "coral",
    "count", "cover", "craft", "crane", "crash", "cream", "creek", "crest",
    "cross", "crown", "crush", "curve", "cycle", "dance", "dawn", "delta",
    "depth", "desk", "diary", "digit", "dock", "dodge", "doubt", "draft",
    "drain", "dream", "drift", "drink", "drive", "drone", "drum", "dusk",
    "eagle", "earth", "echo", "edge", "ember", "enter", "equal", "event",
    "extra", "fable", "faith", "fancy", "feast", "fence", "ferry", "fetch",
    "fiber", "field", "final", "flake", "flame", "flash", "fleet", "flint",
    "float", "flock", "flood", "floor", "flour", "flute", "focal", "foggy",
    "force", "forge", "forth", "forum", "found", "frame", "fresh", "front",
    "frost", "fruit", "gamma", "garlic", "gauge", "gaze", "giant", "glade",
    "gleam", "glide", "globe", "glory", "grace", "grade", "grain", "grand",
    "grant", "grape", "grasp", "grass", "green", "greet", "grill", "grind",
    "grove", "guard", "guide", "habit", "happy", "haven", "heart", "hedge",
    "hello", "heron", "hiker", "honey", "honor", "hover", "human", "humor",
    "hustle", "igloo", "image", "index", "inner", "input", "ivory", "jewel",
    "jolly", "joust", "judge", "juice", "kayak", "knack", "kneel", "knife",
    "knock", "known", "label", "lance", "latch", "layer", "learn", "ledge",
    "lemon", "level", "light", "lilac", "limit", "linen", "lodge", "logic",
    "lotus", "lucky", "lunar", "lunch", "magic", "major", "manor", "maple",
    "march", "marsh", "match", "mayor", "medal", "melon", "mercy", "merge",
    "merit", "merry", "metal", "meter", "might", "minor", "misty", "model",
    "moose", "moral", "motor", "mount", "mouse", "music", "nerve", "never",
    "night", "noble", "north", "noted", "novel", "nurse", "ocean", "olive",
    "onset", "opera", "orbit", "order", "organ", "outer", "oxide", "paint",
    "panel", "paper", "party", "pasta", "patch", "pearl", "pedal", "penny",
    "perch", "phase", "phone", "photo", "piano", "pilot", "pinch", "pixel",
    "pizza", "place", "plain", "plane", "plant", "plate", "plaza", "plume",
    "plump", "point", "polar", "pound", "power", "press", "pride", "prime",
    "print", "prize", "probe", "proud", "prove", "pulse", "punch", "pupil",
    "purse", "quake", "queen", "quest", "quick", "quiet", "quilt", "quota",
    "radar", "radio", "raise", "rally", "ranch", "range", "rapid", "raven",
    "reach", "realm", "relay", "ridge", "right", "rinse", "ripen", "rival",
    "river", "robin", "robot", "rocky", "rouge", "round", "route", "royal",
    "rugby", "ruler", "rumor", "rural", "salad", "sandy", "sauce", "scale",
    "scene", "scope", "scout", "sedan", "shade", "shale", "shape", "share",
    "sharp", "sheep", "shell", "shift", "shine", "shirt", "shore", "shout",
    "sight", "silly", "since", "skate", "skill", "skull", "slate", "sleep",
    "slice", "slide", "slope", "smart", "smile", "smoke", "snack", "snake",
    "solar", "solid", "solve", "sonic", "south", "space", "spare", "spark",
    "speak", "spear", "spell", "spend", "spice", "spike", "spine", "split",
    "spoke", "spoon", "sport", "spray", "squad", "stack", "staff", "stage",
    "stair", "stake", "stamp", "stand", "start", "stash", "state", "steam",
    "steel", "steep", "steer", "stick", "still", "sting", "stock", "stone",
    "stool", "storm", "story", "stove", "strap", "straw", "strip", "strut",
    "study", "stuff", "stump", "style", "sugar", "suite", "sunny", "super",
    "surge", "swamp", "swear", "sweep", "sweet", "swift", "swing", "table",
    "tally", "tango", "teach", "tempo", "thank", "theme", "thing", "think",
    "thorn", "three", "throw", "thumb", "tiger", "timer", "toast", "token",
    "topic", "total", "touch", "tower", "toxic", "trace", "track", "trade",
    "trail", "train", "trait", "trash", "trend", "trial", "trick", "troop",
    "truck", "truly", "trump", "trunk", "trust", "truth", "tulip", "tuner",
    "ultra", "under", "union", "unite", "unity", "upper", "urban", "usual",
    "valid", "valor", "valve", "vault", "verse", "vigor", "vinyl", "viola",
    "viper", "vivid", "vocal", "voice", "voter", "wagon", "watch", "water",
    "weave", "wheat", "wheel", "where", "while", "white", "whole", "width",
    "witch", "world", "wound", "wrist", "wrote", "yacht", "yield", "young",
    "youth", "zebra",
    "amber", "ankle", "atlas", "audio", "bacon", "baron", "basic", "beast",
    "bench", "berry", "bison", "blade", "bliss", "bluff", "booth", "brace",
    "brand", "brass", "bread", "brisk", "broth", "brush", "buyer", "camel",
    "canoe", "cedar", "charm", "chart", "cheek", "cheer", "chess", "child",
    "chord", "chunk", "civil", "claim", "clamp", "cloak", "cloth", "cobra",
    "cocoa", "coral", "couch", "court", "cover", "crane", "crawl", "crown",
    "crush", "dairy", "darts", "decoy", "delve", "depot", "derby", "diner",
    "dizzy", "donor", "drama", "drape", "dress", "dried", "droit", "dwarf",
    "eight", "elbow", "elder", "elite", "ember", "entry", "envoy", "epoch",
    "equip", "erase", "essay", "exact", "exile", "expat", "extra", "facet",
    "fairy", "fault", "feast", "fiber", "finch", "flame", "flask", "fleet",
    "flint", "flora", "focus", "forge", "frame", "frank", "frost", "gamer",
    "ghost", "gloss", "gnome", "goose", "grain", "graph", "graze", "group",
    "guest", "guild", "gummy", "gusto", "haven", "hazel", "hedge", "heist",
    "hippo", "hoard", "honey", "horse", "hotel", "house", "icing", "ideal",
    "inbox", "issue", "ivory", "jelly", "jetty", "joint", "joker", "juice",
    "karma", "kayak", "kinky", "knelt", "koala", "lance", "laser", "latch",
    "layer", "ledge", "lemur", "lever", "llama", "lobby", "lucky", "magma",
    "manor", "marsh", "match", "mayor", "media", "mercy", "midst", "miner",
    "mocha", "month", "mound", "movie", "mural", "myth", "naval", "nifty",
    "nomad", "notch", "nurse", "oasis", "okapi", "omega", "onset", "orbit",
    "otter", "ought", "oxide", "paint", "panda", "panic", "pansy", "party",
    "pasta", "patch", "pause", "peach", "perch", "phase", "piano", "plaid",
    "plank", "plaza", "pluck", "plumb", "plume", "poker", "polar", "pound",
    "power", "prank", "press", "proof", "prune", "puppy", "quota", "queen",
    "quest", "radar", "ranch", "rebel", "reign", "remix", "rider", "ridge",
    "robot", "rogue", "ruler", "salsa", "satin", "savor", "scout", "sedan",
    "setup", "seven", "shark", "shelf", "shift", "shock", "silly", "siren",
    "sixth", "skunk", "sleek", "sleet", "slope", "smart", "snail", "snowy",
    "solar", "sonic", "spade", "spark", "spear", "spice", "spine", "stair",
    "stalk", "stamp", "steam", "steed", "stiff", "stomp", "stork", "stout",
    "strum", "stuff", "sugar", "sunny", "super", "swirl", "table", "tango",
    "teach", "tempo", "thick", "thorn", "tidal", "tiger", "toast", "token",
    "topaz", "torch", "tower", "trace", "track", "train", "trick", "trout",
    "truck", "truly", "tulip", "umbra", "uncle", "unify", "utter", "vapor",
    "verse", "vigor", "viola", "voter", "waltz", "weave", "wedge", "whale",
    "wheat", "whisk", "whole", "width", "winch", "witch", "world", "wrist",
    "yield", "youth", "zebra", "zloty",
    "acorn", "adorn", "agile", "aisle", "album", "alert", "algae", "alien",
    "align", "alley", "alloy", "alter", "angel", "angle", "apart", "arena",
    "awake", "azure", "badge", "baker", "basin", "batch", "beach", "blank",
    "blaze", "blend", "blimp", "bloat", "bloom", "board", "boost", "bound",
    "braid", "brain", "brave", "brief", "bring", "brook", "budge", "cargo",
    "cedar", "chalk", "chant", "chest", "cinch", "civic", "clang", "clash",
    "clasp", "clerk", "click", "climb", "cling", "close", "clout", "comet",
    "comic", "count", "craft", "creek", "creep", "crisp", "cross", "curve",
    "dance", "daisy", "denim", "depth", "dodge", "doubt", "dozen", "draft",
    "drain", "drawn", "dream", "drift", "droit", "drool", "dutch", "dwelt",
    "eagle", "easel", "eight", "ember", "empty", "epoch", "equip", "event",
    "exert", "fable", "fairy", "faith", "feast", "fetch", "fiber", "fifty",
    "final", "flair", "flare", "fling", "flint", "float", "flood", "floss",
    "fluid", "flush", "focal", "foray", "forge", "forum", "found", "frost",
    "funny", "gamma", "gauge", "ghost", "giant", "giddy", "girth", "glass",
    "gleam", "glide", "globe", "glyph", "gnome", "gourd", "grace", "graph",
    "grasp", "grate", "grind", "grout", "guard", "guide", "habit", "haste",
    "haven", "heart", "hinge", "hoist", "horse", "house", "human", "humor",
)
# fmt: on

# Deduplicate while preserving order for deterministic tests
_WORD_LIST: list[str] = list(dict.fromkeys(_WORDS))


def generate_passphrase(word_count: int = 4) -> str:
    """Return a space-separated passphrase of *word_count* random words."""
    return " ".join(secrets.choice(_WORD_LIST) for _ in range(word_count))
