from __future__ import annotations

from typing import Protocol
from uuid import UUID

from dibble.models.curriculum import CurriculumResource, CurriculumResourceUpsert, KnowledgeComponent, KnowledgeComponentUpsert
from dibble.models.assessment import SocraticAssessmentSession
from dibble.models.generation import GeneratedContent, GenerationRequest, PredictiveWarmSweepResult, PredictiveWarmTask
from dibble.models.observations import LearnerObservation, LearnerObservationCreate
from dibble.models.profile import LearnerProfile
from dibble.models.remediation import RemediationWorkflowSession
from dibble.models.session_adaptation import WithinSessionControllerState
from dibble.models.telemetry import AuditEvent, ProviderHealthEvent, ProviderStatusSnapshot
from dibble.services.auth_sessions import StoredAuthSession
from dibble.services.provider_health import ProviderRoutingSnapshot
from dibble.services.retrieval.embedding_store import StoredEmbedding


class ProfileStore(Protocol):
    def upsert(self, profile: LearnerProfile) -> LearnerProfile: ...
    def get(self, student_id: UUID) -> LearnerProfile | None: ...
    def list_ids(self) -> list[str]: ...


class ObservationStore(Protocol):
    def append(self, *, student_id: str, observation: LearnerObservationCreate) -> LearnerObservation: ...
    def list_recent(self, *, student_id: str, limit: int = 20) -> list[LearnerObservation]: ...


class CurriculumStore(Protocol):
    def upsert(self, resource: CurriculumResourceUpsert) -> CurriculumResource: ...
    def get(self, resource_id: str) -> CurriculumResource | None: ...
    def list(self) -> list[CurriculumResource]: ...


class KnowledgeComponentStore(Protocol):
    def upsert(self, component: KnowledgeComponentUpsert) -> KnowledgeComponent: ...
    def get(self, kc_id: str) -> KnowledgeComponent | None: ...
    def list(self) -> list[KnowledgeComponent]: ...
    def list_prerequisites(self, kc_id: str) -> list[KnowledgeComponent]: ...


class AuditStore(Protocol):
    def append(
        self,
        *,
        event_type: str,
        status: str,
        student_id: str | None = None,
        payload: dict[str, object] | None = None,
    ) -> AuditEvent: ...

    def list(self, *, limit: int = 50) -> list[AuditEvent]: ...


class GeneratedContentStore(Protocol):
    def upsert(self, *, cache_key: str, content: GeneratedContent) -> GeneratedContent: ...
    def get(self, *, generation_id: str) -> GeneratedContent | None: ...
    def get_fresh(self, *, cache_key: str) -> GeneratedContent | None: ...
    def refresh(self, *, content: GeneratedContent) -> GeneratedContent: ...
    def list_recent(self, *, limit: int = 50) -> list[GeneratedContent]: ...
    def list_recent_for_student(
        self,
        *,
        student_id: str,
        limit: int = 20,
        include_predictive_warm: bool = False,
    ) -> list[GeneratedContent]: ...
    def expire_predictive_content(
        self,
        *,
        student_id: str | None,
        target_kc_ids: list[str],
        target_lo_ids: list[str],
        learning_session_id: str | None = None,
    ) -> int: ...
    def stats(self) -> dict[str, int]: ...


class PredictiveWarmTaskStore(Protocol):
    def enqueue(self, *, request: GenerationRequest) -> PredictiveWarmTask | None: ...
    def sweep(self, *, limit: int = 200) -> PredictiveWarmSweepResult: ...
    def claim_pending(
        self,
        *,
        limit: int = 10,
        claim_owner: str = "scheduler",
        claim_mode: str = "pending_drain",
        claim_reason: str = "eligible queue backlog",
        stale_recovered_task_ids: list[str] | None = None,
    ) -> list[PredictiveWarmTask]: ...
    def claim_tasks(
        self,
        *,
        task_ids: list[str],
        claim_owner: str = "scheduler",
        claim_mode: str = "targeted",
        claim_reason: str = "targeted queue claim",
        stale_recovered_task_ids: list[str] | None = None,
    ) -> list[PredictiveWarmTask]: ...
    def mark_completed(self, *, task_id: str) -> None: ...
    def mark_failed(self, *, task_id: str, error: str) -> None: ...
    def defer_retry(self, *, task_id: str, error: str) -> PredictiveWarmTask | None: ...
    def cancel_pending(
        self,
        *,
        student_id: str | None,
        target_kc_ids: list[str],
        target_lo_ids: list[str],
        learning_session_id: str | None = None,
    ) -> int: ...
    def stats(self) -> dict[str, int | None]: ...


class EmbeddingStore(Protocol):
    def get(self, resource_id: str) -> StoredEmbedding | None: ...
    def upsert(self, *, resource_id: str, vector: list[float], source_updated_at: str) -> StoredEmbedding: ...


class ProviderHealthStore(Protocol):
    def append(self, *, provider_name: str, status: str, detail: dict[str, object] | None = None) -> ProviderHealthEvent: ...
    def list(self, *, limit: int = 100) -> list[ProviderHealthEvent]: ...
    def latest_statuses(self) -> list[ProviderStatusSnapshot]: ...
    def routing_snapshots(self, *, provider_names: list[str] | None = None, limit: int = 500) -> list[ProviderRoutingSnapshot]: ...


class SocraticSessionStore(Protocol):
    def upsert(self, session: SocraticAssessmentSession) -> SocraticAssessmentSession: ...
    def get(self, session_id: str) -> SocraticAssessmentSession | None: ...
    def list_recent_for_student(self, *, student_id: str, limit: int = 20) -> list[SocraticAssessmentSession]: ...


class RemediationSessionStore(Protocol):
    def upsert(self, session: RemediationWorkflowSession) -> RemediationWorkflowSession: ...
    def get(self, session_id: str) -> RemediationWorkflowSession | None: ...
    def list_recent_for_student(self, *, student_id: str, limit: int = 20) -> list[RemediationWorkflowSession]: ...


class WithinSessionControllerStore(Protocol):
    def upsert(self, session: WithinSessionControllerState) -> WithinSessionControllerState: ...
    def get(self, learning_session_id: str) -> WithinSessionControllerState | None: ...


class AuthSessionStore(Protocol):
    def get(self, session_id: str) -> StoredAuthSession | None: ...
    def upsert(self, session: StoredAuthSession) -> StoredAuthSession: ...
    def revoke(self, session_id: str, *, revoked_at: str) -> None: ...
