from __future__ import annotations

from typing import Protocol
from uuid import UUID

from dibble.models.curriculum import CurriculumResource, CurriculumResourceUpsert, KnowledgeComponent, KnowledgeComponentUpsert
from dibble.models.generation import GeneratedContent
from dibble.models.observations import LearnerObservation, LearnerObservationCreate
from dibble.models.profile import LearnerProfile
from dibble.models.telemetry import AuditEvent, ProviderHealthEvent, ProviderStatusSnapshot
from dibble.services.auth_sessions import StoredAuthSession
from dibble.services.provider_health import ProviderRoutingSnapshot


class ProfileStore(Protocol):
    def upsert(self, profile: LearnerProfile) -> LearnerProfile: ...
    def get(self, student_id: UUID) -> LearnerProfile | None: ...
    def list_ids(self) -> list[str]: ...


class ObservationStore(Protocol):
    def append(self, *, student_id: str, observation: LearnerObservationCreate) -> LearnerObservation: ...
    def list_recent(self, *, student_id: str, limit: int = 20) -> list[LearnerObservation]: ...


class CurriculumStore(Protocol):
    def upsert(self, resource: CurriculumResourceUpsert) -> CurriculumResource: ...
    def get(self, resource_id: str) -> CurriculumResource | None: ...
    def list(self) -> list[CurriculumResource]: ...


class KnowledgeComponentStore(Protocol):
    def upsert(self, component: KnowledgeComponentUpsert) -> KnowledgeComponent: ...
    def get(self, kc_id: str) -> KnowledgeComponent | None: ...
    def list(self) -> list[KnowledgeComponent]: ...
    def list_prerequisites(self, kc_id: str) -> list[KnowledgeComponent]: ...


class AuditStore(Protocol):
    def append(
        self,
        *,
        event_type: str,
        status: str,
        student_id: str | None = None,
        payload: dict[str, object] | None = None,
    ) -> AuditEvent: ...

    def list(self, *, limit: int = 50) -> list[AuditEvent]: ...


class GeneratedContentStore(Protocol):
    def upsert(self, *, cache_key: str, content: GeneratedContent) -> GeneratedContent: ...
    def get_fresh(self, *, cache_key: str) -> GeneratedContent | None: ...
    def stats(self) -> dict[str, int]: ...


class ProviderHealthStore(Protocol):
    def append(self, *, provider_name: str, status: str, detail: dict[str, object] | None = None) -> ProviderHealthEvent: ...
    def list(self, *, limit: int = 100) -> list[ProviderHealthEvent]: ...
    def latest_statuses(self) -> list[ProviderStatusSnapshot]: ...
    def routing_snapshots(self, *, provider_names: list[str] | None = None, limit: int = 500) -> list[ProviderRoutingSnapshot]: ...


class SocraticSessionStore(Protocol):
    def upsert(self, session: object) -> object: ...
    def get(self, session_id: str) -> object | None: ...


class AuthSessionStore(Protocol):
    def get(self, session_id: str) -> StoredAuthSession | None: ...
    def upsert(self, session: StoredAuthSession) -> StoredAuthSession: ...
    def revoke(self, session_id: str, *, revoked_at: str) -> None: ...
