import type {
  FrontendConfig,
  GeneratedContent,
  LearnerFlowSummary,
  LearnerProfileV2,
  ProfileSummary,
  RemediationWorkflowSession,
  SocraticAssessmentResponse,
  SocraticAssessmentSession,
  TeacherContractGap,
} from './types'

export const SAMPLE_STUDENT_ID = '11111111-1111-1111-1111-111111111111'

export const defaultConfig: FrontendConfig = {
  baseUrl: 'http://127.0.0.1:8000',
  apiKey: '',
  bearerToken: '',
  useDemoFallback: true,
}

export const demoProfileSummary: ProfileSummary = {
  student_id: SAMPLE_STUDENT_ID,
  grade_level: '5',
  profile_version: '2.0',
  kc_count: 4,
  lo_count: 2,
  engagement: 'medium',
  frustration: 'low',
  total_load: 0.46,
  confidence_calibration: 0.71,
  help_seeking: 'low',
  calibration: {
    signal: 'positive',
    source: 'profile',
    average_run_outcome_score: 0.78,
    confidence: 0.81,
    matched_run_count: 6,
    matched_session_count: 3,
    intent: 'practice',
    content_type: 'practice_problem',
    target_kc_ids: ['KC-1'],
    target_lo_ids: ['LO-1'],
    updated_at: '2026-03-16T08:45:00Z',
  },
  progress: {
    signal: 'improving',
    source: 'profile',
    average_run_outcome_score: 0.8,
    confidence: 0.79,
    matched_run_count: 6,
    matched_session_count: 3,
    positive_run_rate: 0.83,
    negative_run_rate: 0.0,
    recent_average_run_outcome_score: 0.84,
    prior_average_run_outcome_score: 0.68,
    progress_delta: 0.16,
    updated_at: '2026-03-16T08:45:00Z',
  },
  strategy: {
    signal: 'independence_ready',
    source: 'strategy_profile',
    support_bias: 1,
    recovery_focus: 'independent_practice',
    trajectory_state: 'accelerating',
    recommended_next_action: 'check_transfer_readiness',
    confidence: 0.76,
    average_run_outcome_score: 0.8,
    matched_run_count: 6,
    matched_session_count: 3,
    progress_signal: 'improving',
    progress_delta: 0.16,
    volatility_index: 0.11,
    relapse_risk: 0.12,
    rationale:
      'Recent low-support practice is improving, but transfer checks should stay explicit because prior sessions were more support-dependent.',
    updated_at: '2026-03-16T08:45:00Z',
  },
  state_profile: {
    signal: 'independence_ready',
    source: 'state_profile',
    confidence: 0.77,
    average_run_outcome_score: 0.8,
    matched_run_count: 6,
    matched_session_count: 3,
    progress_signal: 'improving',
    progress_delta: 0.16,
    strategy_signal: 'independence_ready',
    strategy_trajectory_state: 'accelerating',
    engagement: 'medium',
    frustration: 'low',
    total_load: 0.46,
    confidence_calibration: 0.71,
    help_seeking: 'low',
    self_monitoring: 0.74,
    affective_reliability: 0.7,
    load_reliability: 0.68,
    recovery_stability: 0.8,
    overload_risk: 0.21,
    metacognitive_reliability: 0.73,
    rationale:
      'Current observations align with durable recovery and a manageable load profile, so support can fade carefully.',
    updated_at: '2026-03-16T08:45:00Z',
  },
  trait_profile: {
    signal: 'stable',
    source: 'trait_profile',
    matched_observation_count: 18,
    matched_session_count: 5,
    processing_speed: { value: 0.74, confidence: 0.78, assessed_at: '2026-03-16T08:45:00Z' },
    working_memory: { value: 0.69, confidence: 0.75, assessed_at: '2026-03-16T08:45:00Z' },
    spatial_reasoning: { value: 0.64, confidence: 0.63, assessed_at: '2026-03-16T08:45:00Z' },
    processing_speed_reliability: 0.76,
    working_memory_reliability: 0.72,
    spatial_reasoning_reliability: 0.6,
    trait_stability: 0.74,
    challenge_tolerance: 0.67,
    challenge_evidence_strength: 0.71,
    rationale:
      'Processing speed and working memory are stable enough to reduce scaffolds gradually, but not to skip transfer checks.',
    updated_at: '2026-03-16T08:45:00Z',
  },
  recent_activity: {
    generation_count: 9,
    observation_count: 16,
    socratic_assessment_count: 3,
    last_learning_session_id: 'session-fractions-bridge',
    last_generation_id: 'gen-demo-worked-example',
    last_event_at: '2026-03-16T08:51:00Z',
  },
  current_flow: {
    status: 'ready_for_next_step',
    flow_type: 'lesson',
    learning_session_id: 'session-fractions-bridge',
    remediation_session_id: null,
    socratic_session_id: 'soc-demo-1',
    current_phase: 'consolidate',
    current_content_type: 'worked_example',
    last_generation_id: 'gen-demo-worked-example',
    progression_action: 'attempt_transfer',
    target_stage: 'transfer',
    active_target_kc_ids: ['KC-1'],
    deferred_target_kc_ids: [],
    transfer_target_kc_ids: ['KC-1'],
    session_phase: 'consolidate',
    session_arc_action: 'bridge',
    session_stuck_loop_risk: 'low',
    rationale:
      'The learner has recent support-light success on the repair target, so the next step should test transfer on the original KC.',
    next_step: {
      action: 'deliver',
      content_type: 'practice_problem',
      target_stage: 'transfer',
      target_kc_ids: ['KC-1'],
      rationale: 'Run one targeted transfer problem before advancing to broader lesson flow.',
    },
    updated_at: '2026-03-16T08:52:00Z',
  },
  updated_at: '2026-03-16T08:52:00Z',
}

export const demoLearnerFlow: LearnerFlowSummary = demoProfileSummary.current_flow

export const demoProfile: LearnerProfileV2 = {
  profile_metadata: {
    student_id: SAMPLE_STUDENT_ID,
    version: '2.0',
    last_updated: '2026-03-16T08:52:00Z',
    completeness_score: 0.86,
  },
  cognitive_traits: {
    working_memory: { value: 0.69, confidence: 0.75, assessed_at: '2026-03-16T08:45:00Z' },
    processing_speed: { value: 0.74, confidence: 0.78, assessed_at: '2026-03-16T08:45:00Z' },
  },
  knowledge_state: {
    lo_mastery: { 'LO-1': 0.74, 'LO-2': 0.58 },
    kc_mastery: { 'KC-1': 0.81, 'KC-2': 0.62, 'KC-3': 0.57, 'KC-4': 0.49 },
    last_updated: '2026-03-16T08:52:00Z',
  },
  affective_state: {
    engagement: 'medium',
    frustration: 'low',
    confusion: 'low',
    confidence: 0.72,
    inferred_at: '2026-03-16T08:52:00Z',
  },
  cognitive_load: {
    intrinsic_load: 0.48,
    extraneous_load: 0.17,
    germane_load: 0.63,
    total_load: 0.46,
    capacity_utilization: 0.58,
    inferred_at: '2026-03-16T08:52:00Z',
  },
  metacognitive_state: {
    confidence_calibration: 0.71,
    help_seeking: 'low',
    help_seeking_effectiveness: 0.79,
    self_monitoring: 0.74,
    inferred_at: '2026-03-16T08:52:00Z',
  },
  learning_preferences: {
    modality_affinity: {
      textual: 0.78,
      interactive: 0.73,
      visual: 0.62,
      video: 0.41,
    },
    example_domain_preferences: ['music', 'science', 'gaming'],
    scaffolding_preference: 'medium',
    pace_preference: 'average',
  },
  accommodations: ['extended_time'],
}

export const demoGeneration: GeneratedContent = {
  generation_id: 'gen-demo-worked-example',
  student_id: SAMPLE_STUDENT_ID,
  content_type: 'worked_example',
  request_context: {
    learning_session_id: 'session-fractions-bridge',
    progression: {
      action: 'attempt_transfer',
      target_stage: 'transfer',
      target_redirect_applied: false,
    },
  },
  workflow_summary: {
    status: 'delivered',
    flow_type: 'lesson',
    learning_session_id: 'session-fractions-bridge',
    delivered_phase: 'consolidate',
    delivered_content_type: 'worked_example',
    progression_action: 'attempt_transfer',
    target_stage: 'transfer',
    active_target_kc_ids: ['KC-1'],
    rationale:
      'The learner is ready for a bridge from repair back to the real target, but still benefits from one visible model.',
    next_step: {
      action: 'deliver',
      content_type: 'practice_problem',
      target_stage: 'transfer',
      target_kc_ids: ['KC-1'],
      rationale: 'Move to learner-owned practice on the original target KC.',
    },
  },
  response: {
    student_id: SAMPLE_STUDENT_ID,
    generated_at: '2026-03-16T08:50:00Z',
    route: {
      intervention_type: 'targeted_practice',
      delivery_mode: 'generated',
      scaffolding_level: 'medium',
      reasons: [
        'Recent same-session evidence is positive but still prefers an explicit transfer move.',
        'The learner strategy profile recommends checking transfer readiness next.',
      ],
      calibration: {
        signal: 'positive',
        source: 'profile',
        confidence: 0.81,
        average_run_outcome_score: 0.78,
        matched_run_count: 6,
        positive_run_rate: 0.83,
        negative_run_rate: 0,
        progress_signal: 'improving',
        progress_delta: 0.16,
      },
    },
    blocks: [
      {
        kind: 'worked_example',
        title: 'Model The Relationship',
        body:
          'Start with one rectangle split into 2 equal parts and shade 1 part. Next split the same whole into 4 equal parts and shade 2 parts. The amount covered stays the same even though the names change.',
      },
      {
        kind: 'bridge_prompt',
        title: 'Your Turn',
        body:
          'If 3/6 and 1/2 cover the same amount, what stays the same and what changes? Explain using the whole, not just the numbers.',
      },
    ],
    curriculum_context: ['Equivalent fractions'],
    grounding: [
      {
        resource_id: 'CURR-1',
        title: 'Equivalent Fractions Foundations',
        grade_level: '5',
        subject: 'math',
        source_type: 'curriculum_standard',
        score: 0.94,
        matched_terms: ['equivalent fractions', 'visual model'],
        excerpt: 'Use visual fraction models to explain why equivalent fractions name the same amount.',
      },
    ],
    safety_notes: [],
    validation_issues: [],
    generation_id: 'gen-demo-worked-example',
    generation_metadata: {
      quality_score: 0.96,
      validation_passed: true,
      validation_issue_count: 0,
      grounding_count: 1,
      provider_name: 'demo-provider',
      model_used: 'demo-model',
      prompt_template_name: 'worked_example',
      prompt_template_version: '1.0',
      prompt_template_variant: 'baseline',
      generation_latency_ms: 1190,
      cache_hit: false,
      moderation: {
        status: 'clear',
        stage: 'none',
        severity: 'none',
        decision: 'allow',
        categories: [],
        reasons: [],
        matched_terms: [],
        blocked: false,
        request_blocked: false,
        response_rewritten: false,
        fallback_applied: false,
        fallback_kind: null,
        stream_action: 'none',
        provider_invoked: true,
        stream_buffered: false,
        original_block_count: 2,
        replacement_block_count: 0,
        audit_message: null,
      },
    },
  },
  quality: {
    quality_score: 0.96,
    validation_passed: true,
    validation_issue_count: 0,
    grounding_count: 1,
    provider_name: 'demo-provider',
    model_used: 'demo-model',
    prompt_template_name: 'worked_example',
    prompt_template_version: '1.0',
    prompt_template_variant: 'baseline',
    generation_latency_ms: 1190,
    cache_hit: false,
    moderation: {
      status: 'clear',
      stage: 'none',
      severity: 'none',
      decision: 'allow',
      categories: [],
      reasons: [],
      matched_terms: [],
      blocked: false,
      request_blocked: false,
      response_rewritten: false,
      fallback_applied: false,
      fallback_kind: null,
      stream_action: 'none',
      provider_invoked: true,
      stream_buffered: false,
      original_block_count: 2,
      replacement_block_count: 0,
      audit_message: null,
    },
  },
  created_at: '2026-03-16T08:50:00Z',
  expires_at: null,
}

export const demoSocraticResponse: SocraticAssessmentResponse = {
  session_id: 'soc-demo-1',
  student_id: SAMPLE_STUDENT_ID,
  learning_session_id: 'session-fractions-bridge',
  turn_id: 'turn-demo-2',
  prompt: 'What would stay the same if we changed 1/2 into 3/6?',
  prompt_style: 'transfer_check',
  steering_action: 'verify_transfer',
  policy_rationale:
    'Recent learner language shows grounded understanding, so the next turn should test whether they can transfer the idea to a new equivalent pair.',
  evaluation: {
    evidence_strength: 'demonstrated',
    evidence_score: 0.78,
    evidence_dimensions: {
      lexical_alignment: 0.82,
      reasoning_signal: 0.8,
      confidence_alignment: 0.74,
      progression_signal: 0.79,
      misconception_risk: 0.12,
    },
    inferred_mastery: 0.86,
    matched_terms: ['same amount', 'whole', 'equal parts'],
    rationale:
      'The learner explained the relationship in terms of the same whole and equal space, which is good evidence of conceptual understanding.',
    next_action: 'advance',
  },
  route: demoGeneration.response.route,
  grounding: demoGeneration.response.grounding,
  generated_blocks: [
    {
      kind: 'assessment_probe',
      title: 'Socratic Prompt',
      body: 'How would you prove that 3/6 still names the same amount as 1/2?',
    },
  ],
  conversation_history: [
    { role: 'tutor', text: 'Why might 1/2 and 2/4 represent the same amount?' },
    {
      role: 'learner',
      text: 'Because the whole is the same and both pictures cover equal space even with different numbers.',
    },
  ],
  summary: {
    status: 'ready_for_follow_up',
    turn_count: 2,
    latest_prompt_style: 'transfer_check',
    latest_steering_action: 'verify_transfer',
    latest_next_action: 'advance',
    latest_evidence_strength: 'demonstrated',
    latest_evidence_score: 0.78,
    rationale: 'Move from explanation checking into transfer practice on the same KC.',
    next_step: {
      action: 'deliver',
      content_type: 'practice_problem',
      target_stage: 'transfer',
      target_kc_ids: ['KC-1'],
      rationale: 'The next step should test transfer with learner-owned work.',
    },
    updated_at: '2026-03-16T08:52:00Z',
  },
  generation_id: 'soc-gen-demo-1',
  generation_metadata: demoGeneration.quality,
  created_at: '2026-03-16T08:52:00Z',
}

export const demoSocraticSession: SocraticAssessmentSession = {
  session_id: 'soc-demo-1',
  student_id: SAMPLE_STUDENT_ID,
  learning_session_id: 'session-fractions-bridge',
  target_kc_ids: ['KC-1'],
  target_lo_ids: ['LO-1'],
  curriculum_context: ['Equivalent fractions'],
  conversation_history: demoSocraticResponse.conversation_history,
  turns: [
    {
      turn_id: 'turn-demo-1',
      prompt: 'Why might 1/2 and 2/4 represent the same amount?',
      prompt_style: 'diagnostic',
      steering_action: 'open_probe',
      policy_rationale: 'Start with an open conceptual explanation.',
      learner_response:
        'Because even though the numbers are different, the same whole is shaded.',
      evaluation: {
        evidence_strength: 'emerging',
        evidence_score: 0.63,
        evidence_dimensions: {
          lexical_alignment: 0.69,
          reasoning_signal: 0.65,
          confidence_alignment: 0.6,
          progression_signal: 0.66,
          misconception_risk: 0.21,
        },
        inferred_mastery: 0.73,
        matched_terms: ['same whole', 'different numbers'],
        rationale: 'The learner is close, but a transfer check is still useful.',
        next_action: 'advance',
      },
      created_at: '2026-03-16T08:49:00Z',
    },
    {
      turn_id: demoSocraticResponse.turn_id,
      prompt: demoSocraticResponse.prompt,
      prompt_style: demoSocraticResponse.prompt_style,
      steering_action: demoSocraticResponse.steering_action,
      policy_rationale: demoSocraticResponse.policy_rationale,
      learner_response:
        'If the whole stays the same, splitting it into more equal parts just changes the name, not the amount.',
      evaluation: demoSocraticResponse.evaluation,
      created_at: '2026-03-16T08:52:00Z',
    },
  ],
  summary: demoSocraticResponse.summary,
  created_at: '2026-03-16T08:49:00Z',
  updated_at: '2026-03-16T08:52:00Z',
}

export const demoRemediationSession: RemediationWorkflowSession = {
  session_id: 'rem-demo-1',
  student_id: SAMPLE_STUDENT_ID,
  target_kc_id: 'KC-2',
  focus_kc_ids: ['KC-1', 'KC-2'],
  prerequisite_kc_ids: ['KC-1'],
  misconception_description: 'The learner compares numerator and denominator separately instead of the full amount.',
  curriculum_context: ['Equivalent fractions'],
  rationale:
    'Repeated misconception evidence points to a prerequisite visual-whole understanding gap, so repair should begin on KC-1 before returning to KC-2.',
  blueprint: {
    recurrence_signal: 'recurring',
    selected_focus: 'visual whole comparison',
  },
  strategy_summary: demoProfileSummary.strategy,
  kc_sequence: {
    action: 'rebuild_prerequisite_first',
    primary_kc_id: 'KC-1',
    ordered_kc_ids: ['KC-1', 'KC-2'],
    bridge_kc_ids: ['KC-bridge-1'],
    deferred_kc_ids: [],
    rationale: 'Repair the prerequisite visual-whole model before attempting the original target KC.',
  },
  steps: [
    {
      phase: 'step_back',
      title: 'Reconnect The Whole',
      target_kc_ids: ['KC-1'],
      support_level: 'high',
      objective: 'Rebuild the idea that equivalent fractions name the same whole amount.',
      guidance: 'Use one whole and compare shaded area before naming parts.',
      misconception_ids: ['fraction-whole-number-bias'],
      recommended_content_type: 'remedial_micro_module',
      status: 'completed',
      generated_content_id: 'gen-demo-step-back',
    },
    {
      phase: 'repair',
      title: 'Repair The Comparison Rule',
      target_kc_ids: ['KC-1'],
      support_level: 'medium',
      objective: 'Compare fractions by whole amount instead of separate numerator and denominator cues.',
      guidance: 'Ask the learner to justify sameness using the picture and the whole.',
      misconception_ids: ['fraction-whole-number-bias'],
      recommended_content_type: 'worked_example',
      status: 'in_progress',
      generated_content_id: 'gen-demo-worked-example',
    },
    {
      phase: 'return',
      title: 'Return To Target',
      target_kc_ids: ['KC-2'],
      support_level: 'medium',
      objective: 'Reconnect the repaired understanding to the original target KC.',
      guidance: 'Bridge the repaired whole model back to the original comparison task.',
      misconception_ids: ['fraction-whole-number-bias'],
      recommended_content_type: 'practice_problem',
      status: 'pending',
      generated_content_id: null,
    },
  ],
  current_step_index: 1,
  completed_generation_ids: ['gen-demo-step-back', 'gen-demo-worked-example'],
  progression_decision: 'held',
  progression_rationale:
    'Recent linked evidence is still support-heavy, so the workflow should stay on the repair target before returning.',
  progression_target_kc_ids: ['KC-1'],
  summary: {
    status: 'held',
    current_phase: 'repair',
    current_step_title: 'Repair The Comparison Rule',
    current_step_target_kc_ids: ['KC-1'],
    next_phase: 'return',
    completed_step_count: 1,
    step_count: 3,
    progression_decision: 'held',
    progression_rationale:
      'Hold on the repair target until the learner shows stronger low-support evidence.',
    progression_target_kc_ids: ['KC-1'],
    next_step: {
      action: 'deliver',
      content_type: 'worked_example',
      target_stage: 'repair',
      target_kc_ids: ['KC-1'],
      rationale: 'Stay on the repair target and reduce support only if the learner explains the whole correctly.',
    },
  },
  created_at: '2026-03-16T08:35:00Z',
  updated_at: '2026-03-16T08:53:00Z',
}

export const teacherContractGaps: TeacherContractGap[] = [
  {
    severity: 'P0',
    title: 'No teacher override or approval write path',
    why_it_matters:
      'The revised spec calls for explainability and intervention control, but teachers cannot yet accept, reject, or override a generated recommendation from the API.',
    current_backend:
      'The backend returns rationale-rich summaries and workflow metadata, but there is no teacher action endpoint for override, approval, or intervention assignment.',
    frontend_response:
      'Render explainability and recommended next steps clearly, but keep override controls visibly non-destructive and labeled as future backend-owned actions.',
  },
  {
    severity: 'P0',
    title: 'No cohort or classroom dashboard read model',
    why_it_matters:
      'Teacher-facing intervention work usually begins with a class-level triage surface, not a single learner view.',
    current_backend:
      'The API exposes single-learner summary, profile, and flow contracts plus admin observability, but not a teacher-scoped cohort summary or at-risk learner list.',
    frontend_response:
      'Ship the first teacher surface as a learner detail and explainability workspace, not as a full classroom operations dashboard.',
  },
  {
    severity: 'P1',
    title: 'No history or list endpoints for generated runs and sessions',
    why_it_matters:
      'Teachers need to review prior remediation arcs, Socratic traces, and generated artifacts without pasting session IDs manually.',
    current_backend:
      'The API can fetch a remediation or Socratic session by ID and returns generation details inline, but there is no per-learner listing endpoint for sessions or generated content.',
    frontend_response:
      'Expose the active or most recent workflow well, and keep session lookups as direct-ID utilities until history endpoints land.',
  },
  {
    severity: 'P1',
    title: 'Course progression is still local, not course-owned',
    why_it_matters:
      'The frontend should not decide the learner’s next unit or lesson when the revised system wants backend-owned progression.',
    current_backend:
      'Current flow and workflow summaries are stable enough for local next-step rendering, but broader curriculum-to-course orchestration is still partial.',
    frontend_response:
      'Treat `current_flow` and workflow summaries as the authoritative next-step contract and avoid building UI logic that invents course progression.',
  },
  {
    severity: 'P2',
    title: 'No multimodal artifact contract yet',
    why_it_matters:
      'The revised spec includes diagrams and richer media, but the current generation contract is still text-block oriented.',
    current_backend:
      'Generated content returns block lists, grounding, moderation, and workflow metadata only. There is no diagram, simulation, or asset payload shape yet.',
    frontend_response:
      'Design blocks as extensible cards and reserve space for future visual artifacts without pretending the data exists today.',
  },
  {
    severity: 'P2',
    title: 'Teacher-facing analytics are admin-biased today',
    why_it_matters:
      'The system has observability data, but teachers should not need admin audit access to understand why a learner is being held or redirected.',
    current_backend:
      'Audit and metrics endpoints are admin-only; teacher-safe explainability has to come from summary contracts rather than telemetry feeds.',
    frontend_response:
      'Use summary read models and rationale fields as the teacher UI source of truth, and keep raw telemetry as a developer/admin tool only.',
  },
]
