import type {
  FrontendConfig,
  GeneratedContent,
  LearnerContinueAction,
  LearnerCurriculumProgressionSummary,
  LearnerFlowSummary,
  LearnerGenerationHistoryEntry,
  LearnerProfileV2,
  LearnerRemediationSessionHistoryEntry,
  LearnerSocraticSessionHistoryEntry,
  LearnerWorkspace,
  ProfileSummary,
  RemediationWorkflowSession,
  SocraticAssessmentResponse,
  SocraticAssessmentSession,
  TeacherClassroomOverview,
  TeacherClassroomReadModel,
  TeacherContractGap,
  TeacherLearnerCard,
  TeacherInterventionActionContract,
} from './types'

export const SAMPLE_STUDENT_ID = '11111111-1111-1111-1111-111111111111'

export const defaultConfig: FrontendConfig = {
  baseUrl: 'http://127.0.0.1:8000',
  apiKey: '',
  bearerToken: '',
  useDemoFallback: true,
  showDebugPanels: false,
}

const practiceContinueAction: LearnerContinueAction = {
  kind: 'generate_follow_up',
  method: 'POST',
  endpoint: '/api/content/generate',
  resource_id: 'gen-demo-worked-example',
  generation_id: 'gen-demo-worked-example',
  learning_session_id: 'session-fractions-bridge',
  content_type: 'practice_problem',
  target_stage: 'transfer',
  target_kc_ids: ['KC-1'],
  request_payload: {
    student_id: SAMPLE_STUDENT_ID,
    learning_session_id: 'session-fractions-bridge',
    generation_id: 'gen-demo-worked-example',
    source_generation_id: 'gen-demo-worked-example',
    target_kc_ids: ['KC-1'],
    target_lo_ids: ['LO-1'],
    requested_content_type: 'practice_problem',
    intent: 'practice',
    curriculum_context: ['Equivalent fractions'],
  },
  rationale: 'Resume the learner at the transfer practice step the backend already selected.',
}

export const demoCurriculumProgression: LearnerCurriculumProgressionSummary = {
  status: 'active_curriculum_focus',
  source: 'knowledge_state_and_flow',
  flow_type: 'lesson',
  current_stage: 'transfer',
  progression_action: 'attempt_transfer',
  active_target_kc_ids: ['KC-1'],
  resource_count: 3,
  mastered_resource_count: 1,
  ready_resource_count: 1,
  blocked_resource_count: 1,
  active_resource_count: 1,
  mastered_resource_ratio: 0.33,
  current_resource: {
    resource_id: 'CURR-2',
    title: 'Equivalent Fraction Practice',
    state: 'active',
    learning_objective_ids: ['LO-1'],
    knowledge_component_ids: ['KC-1'],
    blocked_prerequisite_kc_ids: [],
    mastery_ratio: 0.81,
    current_flow_aligned: true,
    target_stage: 'transfer',
    rationale: "This resource aligns with the learner's current transfer-ready target.",
  },
  next_resource: {
    resource_id: 'CURR-3',
    title: 'Compare Fraction Families',
    state: 'ready',
    learning_objective_ids: ['LO-2'],
    knowledge_component_ids: ['KC-2'],
    blocked_prerequisite_kc_ids: [],
    mastery_ratio: 0.62,
    current_flow_aligned: false,
    target_stage: 'target',
    rationale: 'This resource is the next curriculum move once current transfer evidence is confirmed.',
  },
  blocked_resources: [
    {
      resource_id: 'CURR-4',
      title: 'Fraction Word Problems',
      state: 'blocked',
      learning_objective_ids: ['LO-3'],
      knowledge_component_ids: ['KC-3'],
      blocked_prerequisite_kc_ids: ['KC-2'],
      mastery_ratio: 0.57,
      current_flow_aligned: false,
      target_stage: 'target',
      rationale: 'The learner should not advance here until the prerequisite comparison KC is more stable.',
    },
  ],
  ready_resources: [
    {
      resource_id: 'CURR-3',
      title: 'Compare Fraction Families',
      state: 'ready',
      learning_objective_ids: ['LO-2'],
      knowledge_component_ids: ['KC-2'],
      blocked_prerequisite_kc_ids: [],
      mastery_ratio: 0.62,
      current_flow_aligned: false,
      target_stage: 'target',
      rationale: 'Ready once the current transfer check finishes.',
    },
  ],
  rationale:
    'The learner is in an active fraction-practice resource with one blocked downstream resource and one next-ready move.',
  updated_at: '2026-03-16T08:54:00Z',
}

export const demoProfileSummary: ProfileSummary = {
  student_id: SAMPLE_STUDENT_ID,
  grade_level: '5',
  profile_version: '2.0',
  kc_count: 4,
  lo_count: 2,
  engagement: 'medium',
  frustration: 'low',
  total_load: 0.46,
  confidence_calibration: 0.71,
  help_seeking: 'low',
  calibration: {
    signal: 'positive',
    source: 'profile',
    average_run_outcome_score: 0.78,
    confidence: 0.81,
    matched_run_count: 6,
    matched_session_count: 3,
    intent: 'practice',
    content_type: 'practice_problem',
    target_kc_ids: ['KC-1'],
    target_lo_ids: ['LO-1'],
    updated_at: '2026-03-16T08:45:00Z',
  },
  progress: {
    signal: 'improving',
    source: 'profile',
    average_run_outcome_score: 0.8,
    confidence: 0.79,
    matched_run_count: 6,
    matched_session_count: 3,
    positive_run_rate: 0.83,
    negative_run_rate: 0.0,
    recent_average_run_outcome_score: 0.84,
    prior_average_run_outcome_score: 0.68,
    progress_delta: 0.16,
    updated_at: '2026-03-16T08:45:00Z',
  },
  strategy: {
    signal: 'independence_ready',
    source: 'strategy_profile',
    support_bias: 1,
    recovery_focus: 'independent_practice',
    trajectory_state: 'accelerating',
    recommended_next_action: 'check_transfer_readiness',
    confidence: 0.76,
    average_run_outcome_score: 0.8,
    matched_run_count: 6,
    matched_session_count: 3,
    progress_signal: 'improving',
    progress_delta: 0.16,
    volatility_index: 0.11,
    relapse_risk: 0.12,
    rationale:
      'Recent low-support practice is improving, but transfer checks should stay explicit because prior sessions were more support-dependent.',
    updated_at: '2026-03-16T08:45:00Z',
  },
  state_profile: {
    signal: 'independence_ready',
    source: 'state_profile',
    confidence: 0.77,
    average_run_outcome_score: 0.8,
    matched_run_count: 6,
    matched_session_count: 3,
    progress_signal: 'improving',
    progress_delta: 0.16,
    strategy_signal: 'independence_ready',
    strategy_trajectory_state: 'accelerating',
    engagement: 'medium',
    frustration: 'low',
    total_load: 0.46,
    confidence_calibration: 0.71,
    help_seeking: 'low',
    self_monitoring: 0.74,
    affective_reliability: 0.7,
    load_reliability: 0.68,
    recovery_stability: 0.8,
    overload_risk: 0.21,
    metacognitive_reliability: 0.73,
    rationale:
      'Current observations align with durable recovery and a manageable load profile, so support can fade carefully.',
    updated_at: '2026-03-16T08:45:00Z',
  },
  trait_profile: {
    signal: 'stable',
    source: 'trait_profile',
    matched_observation_count: 18,
    matched_session_count: 5,
    processing_speed: { value: 0.74, confidence: 0.78, assessed_at: '2026-03-16T08:45:00Z' },
    working_memory: { value: 0.69, confidence: 0.75, assessed_at: '2026-03-16T08:45:00Z' },
    spatial_reasoning: { value: 0.64, confidence: 0.63, assessed_at: '2026-03-16T08:45:00Z' },
    processing_speed_reliability: 0.76,
    working_memory_reliability: 0.72,
    spatial_reasoning_reliability: 0.6,
    trait_stability: 0.74,
    challenge_tolerance: 0.67,
    challenge_evidence_strength: 0.71,
    rationale:
      'Processing speed and working memory are stable enough to reduce scaffolds gradually, but not to skip transfer checks.',
    updated_at: '2026-03-16T08:45:00Z',
  },
  state_prediction_reliability: {
    evaluated_count: 8,
    overall_accuracy: 0.75,
    weighted_accuracy: 0.78,
    weakest_classification: 'support_dependence',
    strongest_classification: 'overload',
    per_classification: [
      { classification: 'overload', evaluated_count: 3, accuracy_rate: 1.0 },
      { classification: 'productive_struggle', evaluated_count: 3, accuracy_rate: 0.667 },
      { classification: 'support_dependence', evaluated_count: 2, accuracy_rate: 0.5 },
    ],
    rationale:
      'State prediction accuracy: 75% overall (78% recency-weighted) across 8 evaluated predictions. Strongest: overload (100% accuracy, 3 evaluated). Weakest: support_dependence (50% accuracy, 2 evaluated).',
  },
  signal_consistency: {
    divergence_count: 0,
    coherence_score: 1.0,
    high_count: 0,
    medium_count: 0,
    low_count: 0,
    divergences: [],
    rationale: 'All evidence sources are directionally consistent.',
  },
  recent_activity: {
    generation_count: 9,
    observation_count: 16,
    socratic_assessment_count: 3,
    last_learning_session_id: 'session-fractions-bridge',
    last_generation_id: 'gen-demo-worked-example',
    last_event_at: '2026-03-16T08:51:00Z',
  },
  current_flow: {
    status: 'ready_for_next_step',
    flow_type: 'lesson',
    learning_session_id: 'session-fractions-bridge',
    remediation_session_id: null,
    socratic_session_id: 'soc-demo-1',
    current_phase: 'consolidate',
    current_content_type: 'worked_example',
    last_generation_id: 'gen-demo-worked-example',
    progression_action: 'attempt_transfer',
    target_stage: 'transfer',
    active_target_kc_ids: ['KC-1'],
    deferred_target_kc_ids: [],
    transfer_target_kc_ids: ['KC-1'],
    session_phase: 'consolidate',
    session_arc_action: 'bridge',
    session_stuck_loop_risk: 'low',
    rationale:
      'The learner has recent support-light success on the repair target, so the next step should test transfer on the original KC.',
    progression_source: 'learner_flow_policy',
    next_step_source: 'learner_flow_policy',
    next_step: {
      action: 'deliver',
      content_type: 'practice_problem',
      target_stage: 'transfer',
      target_kc_ids: ['KC-1'],
      rationale: 'Run one targeted transfer problem before advancing to broader lesson flow.',
    },
    continue_action: practiceContinueAction,
    updated_at: '2026-03-16T08:52:00Z',
  },
  curriculum_progression: demoCurriculumProgression,
  updated_at: '2026-03-16T08:52:00Z',
}

export const demoLearnerFlow: LearnerFlowSummary = demoProfileSummary.current_flow

export const demoProfile: LearnerProfileV2 = {
  profile_metadata: {
    student_id: SAMPLE_STUDENT_ID,
    version: '2.0',
    last_updated: '2026-03-16T08:52:00Z',
    completeness_score: 0.86,
  },
  cognitive_traits: {
    working_memory: { value: 0.69, confidence: 0.75, assessed_at: '2026-03-16T08:45:00Z' },
    processing_speed: { value: 0.74, confidence: 0.78, assessed_at: '2026-03-16T08:45:00Z' },
  },
  knowledge_state: {
    lo_mastery: { 'LO-1': 0.74, 'LO-2': 0.58 },
    kc_mastery: { 'KC-1': 0.81, 'KC-2': 0.62, 'KC-3': 0.57, 'KC-4': 0.49 },
    last_updated: '2026-03-16T08:52:00Z',
  },
  affective_state: {
    engagement: 'medium',
    frustration: 'low',
    confusion: 'low',
    confidence: 0.72,
    inferred_at: '2026-03-16T08:52:00Z',
  },
  cognitive_load: {
    intrinsic_load: 0.48,
    extraneous_load: 0.17,
    germane_load: 0.63,
    total_load: 0.46,
    capacity_utilization: 0.58,
    inferred_at: '2026-03-16T08:52:00Z',
  },
  metacognitive_state: {
    confidence_calibration: 0.71,
    help_seeking: 'low',
    help_seeking_effectiveness: 0.79,
    self_monitoring: 0.74,
    inferred_at: '2026-03-16T08:52:00Z',
  },
  learning_preferences: {
    modality_affinity: {
      textual: 0.78,
      interactive: 0.73,
      visual: 0.62,
      video: 0.41,
    },
    example_domain_preferences: ['music', 'science', 'gaming'],
    scaffolding_preference: 'medium',
    pace_preference: 'average',
  },
  accommodations: ['extended_time'],
}

export const demoGeneration: GeneratedContent = {
  generation_id: 'gen-demo-worked-example',
  student_id: SAMPLE_STUDENT_ID,
  content_type: 'worked_example',
  request_context: {
    learning_session_id: 'session-fractions-bridge',
    progression: {
      action: 'attempt_transfer',
      target_stage: 'transfer',
      target_redirect_applied: false,
    },
  },
  workflow_summary: {
    status: 'delivered',
    flow_type: 'lesson',
    learning_session_id: 'session-fractions-bridge',
    delivered_phase: 'consolidate',
    delivered_content_type: 'worked_example',
    progression_action: 'attempt_transfer',
    target_stage: 'transfer',
    active_target_kc_ids: ['KC-1'],
    rationale:
      'The learner is ready for a bridge from repair back to the real target, but still benefits from one visible model.',
    next_step: {
      action: 'deliver',
      content_type: 'practice_problem',
      target_stage: 'transfer',
      target_kc_ids: ['KC-1'],
      rationale: 'Move to learner-owned practice on the original target KC.',
    },
    continue_action: practiceContinueAction,
  },
  response: {
    student_id: SAMPLE_STUDENT_ID,
    generated_at: '2026-03-16T08:50:00Z',
    route: {
      intervention_type: 'targeted_practice',
      delivery_mode: 'generated',
      scaffolding_level: 'medium',
      reasons: [
        'Recent same-session evidence is positive but still prefers an explicit transfer move.',
        'The learner strategy profile recommends checking transfer readiness next.',
      ],
      calibration: {
        signal: 'positive',
        source: 'profile',
        confidence: 0.81,
        average_run_outcome_score: 0.78,
        matched_run_count: 6,
        positive_run_rate: 0.83,
        negative_run_rate: 0,
        progress_signal: 'improving',
        progress_delta: 0.16,
      },
    },
    blocks: [
      {
        kind: 'worked_example',
        title: 'Model The Relationship',
        body:
          'Start with one rectangle split into 2 equal parts and shade 1 part. Next split the same whole into 4 equal parts and shade 2 parts. The amount covered stays the same even though the names change.',
      },
      {
        kind: 'bridge_prompt',
        title: 'Your Turn',
        body:
          'If 3/6 and 1/2 cover the same amount, what stays the same and what changes? Explain using the whole, not just the numbers.',
      },
    ],
    curriculum_context: ['Equivalent fractions'],
    grounding: [
      {
        resource_id: 'CURR-1',
        title: 'Equivalent Fractions Foundations',
        grade_level: '5',
        subject: 'math',
        source_type: 'curriculum_standard',
        score: 0.94,
        matched_terms: ['equivalent fractions', 'visual model'],
        excerpt: 'Use visual fraction models to explain why equivalent fractions name the same amount.',
      },
    ],
    safety_notes: [],
    validation_issues: [],
    generation_id: 'gen-demo-worked-example',
    generation_metadata: {
      quality_score: 0.96,
      validation_passed: true,
      validation_issue_count: 0,
      grounding_count: 1,
      provider_name: 'demo-provider',
      model_used: 'demo-model',
      prompt_template_name: 'worked_example',
      prompt_template_version: '1.0',
      prompt_template_variant: 'baseline',
      generation_latency_ms: 1190,
      cache_hit: false,
      moderation: {
        status: 'clear',
        stage: 'none',
        severity: 'none',
        decision: 'allow',
        categories: [],
        reasons: [],
        matched_terms: [],
        blocked: false,
        request_blocked: false,
        response_rewritten: false,
        fallback_applied: false,
        fallback_kind: null,
        stream_action: 'none',
        provider_invoked: true,
        stream_buffered: false,
        original_block_count: 2,
        replacement_block_count: 0,
        audit_message: null,
      },
    },
  },
  quality: {
    quality_score: 0.96,
    validation_passed: true,
    validation_issue_count: 0,
    grounding_count: 1,
    provider_name: 'demo-provider',
    model_used: 'demo-model',
    prompt_template_name: 'worked_example',
    prompt_template_version: '1.0',
    prompt_template_variant: 'baseline',
    generation_latency_ms: 1190,
    cache_hit: false,
    moderation: {
      status: 'clear',
      stage: 'none',
      severity: 'none',
      decision: 'allow',
      categories: [],
      reasons: [],
      matched_terms: [],
      blocked: false,
      request_blocked: false,
      response_rewritten: false,
      fallback_applied: false,
      fallback_kind: null,
      stream_action: 'none',
      provider_invoked: true,
      stream_buffered: false,
      original_block_count: 2,
      replacement_block_count: 0,
      audit_message: null,
    },
  },
  created_at: '2026-03-16T08:50:00Z',
  expires_at: null,
}

export const demoSocraticResponse: SocraticAssessmentResponse = {
  session_id: 'soc-demo-1',
  student_id: SAMPLE_STUDENT_ID,
  learning_session_id: 'session-fractions-bridge',
  turn_id: 'turn-demo-2',
  prompt: 'What would stay the same if we changed 1/2 into 3/6?',
  prompt_style: 'transfer_check',
  steering_action: 'verify_transfer',
  policy_rationale:
    'Recent learner language shows grounded understanding, so the next turn should test whether they can transfer the idea to a new equivalent pair.',
  evaluation: {
    evidence_strength: 'demonstrated',
    evidence_score: 0.78,
    evidence_dimensions: {
      lexical_alignment: 0.82,
      reasoning_signal: 0.8,
      confidence_alignment: 0.74,
      progression_signal: 0.79,
      misconception_risk: 0.12,
    },
    inferred_mastery: 0.86,
    matched_terms: ['same amount', 'whole', 'equal parts'],
    rationale:
      'The learner explained the relationship in terms of the same whole and equal space, which is good evidence of conceptual understanding.',
    next_action: 'advance',
  },
  route: demoGeneration.response.route,
  grounding: demoGeneration.response.grounding,
  generated_blocks: [
    {
      kind: 'assessment_probe',
      title: 'Socratic Prompt',
      body: 'How would you prove that 3/6 still names the same amount as 1/2?',
    },
  ],
  conversation_history: [
    { role: 'tutor', text: 'Why might 1/2 and 2/4 represent the same amount?' },
    {
      role: 'learner',
      text: 'Because the whole is the same and both pictures cover equal space even with different numbers.',
    },
  ],
  summary: {
    status: 'ready_for_follow_up',
    turn_count: 2,
    latest_prompt_style: 'transfer_check',
    latest_steering_action: 'verify_transfer',
    latest_next_action: 'advance',
    latest_evidence_strength: 'demonstrated',
    latest_evidence_score: 0.78,
    rationale: 'Move from explanation checking into transfer practice on the same KC.',
    next_step: {
      action: 'deliver',
      content_type: 'practice_problem',
      target_stage: 'transfer',
      target_kc_ids: ['KC-1'],
      rationale: 'The next step should test transfer with learner-owned work.',
    },
    continue_action: practiceContinueAction,
    updated_at: '2026-03-16T08:52:00Z',
  },
  generation_id: 'soc-gen-demo-1',
  generation_metadata: demoGeneration.quality,
  created_at: '2026-03-16T08:52:00Z',
}

export const demoSocraticSession: SocraticAssessmentSession = {
  session_id: 'soc-demo-1',
  student_id: SAMPLE_STUDENT_ID,
  learning_session_id: 'session-fractions-bridge',
  target_kc_ids: ['KC-1'],
  target_lo_ids: ['LO-1'],
  curriculum_context: ['Equivalent fractions'],
  conversation_history: demoSocraticResponse.conversation_history,
  turns: [
    {
      turn_id: 'turn-demo-1',
      prompt: 'Why might 1/2 and 2/4 represent the same amount?',
      prompt_style: 'diagnostic',
      steering_action: 'open_probe',
      policy_rationale: 'Start with an open conceptual explanation.',
      learner_response:
        'Because even though the numbers are different, the same whole is shaded.',
      evaluation: {
        evidence_strength: 'emerging',
        evidence_score: 0.63,
        evidence_dimensions: {
          lexical_alignment: 0.69,
          reasoning_signal: 0.65,
          confidence_alignment: 0.6,
          progression_signal: 0.66,
          misconception_risk: 0.21,
        },
        inferred_mastery: 0.73,
        matched_terms: ['same whole', 'different numbers'],
        rationale: 'The learner is close, but a transfer check is still useful.',
        next_action: 'advance',
      },
      created_at: '2026-03-16T08:49:00Z',
    },
    {
      turn_id: demoSocraticResponse.turn_id,
      prompt: demoSocraticResponse.prompt,
      prompt_style: demoSocraticResponse.prompt_style,
      steering_action: demoSocraticResponse.steering_action,
      policy_rationale: demoSocraticResponse.policy_rationale,
      learner_response:
        'If the whole stays the same, splitting it into more equal parts just changes the name, not the amount.',
      evaluation: demoSocraticResponse.evaluation,
      created_at: '2026-03-16T08:52:00Z',
    },
  ],
  summary: demoSocraticResponse.summary,
  created_at: '2026-03-16T08:49:00Z',
  updated_at: '2026-03-16T08:52:00Z',
}

export const demoRemediationSession: RemediationWorkflowSession = {
  session_id: 'rem-demo-1',
  student_id: SAMPLE_STUDENT_ID,
  target_kc_id: 'KC-2',
  focus_kc_ids: ['KC-1', 'KC-2'],
  prerequisite_kc_ids: ['KC-1'],
  misconception_description: 'The learner compares numerator and denominator separately instead of the full amount.',
  curriculum_context: ['Equivalent fractions'],
  rationale:
    'Repeated misconception evidence points to a prerequisite visual-whole understanding gap, so repair should begin on KC-1 before returning to KC-2.',
  blueprint: {
    recurrence_signal: 'recurring',
    selected_focus: 'visual whole comparison',
  },
  strategy_summary: demoProfileSummary.strategy,
  kc_sequence: {
    action: 'rebuild_prerequisite_first',
    primary_kc_id: 'KC-1',
    ordered_kc_ids: ['KC-1', 'KC-2'],
    bridge_kc_ids: ['KC-bridge-1'],
    deferred_kc_ids: [],
    rationale: 'Repair the prerequisite visual-whole model before attempting the original target KC.',
  },
  steps: [
    {
      phase: 'step_back',
      title: 'Reconnect The Whole',
      target_kc_ids: ['KC-1'],
      support_level: 'high',
      objective: 'Rebuild the idea that equivalent fractions name the same whole amount.',
      guidance: 'Use one whole and compare shaded area before naming parts.',
      misconception_ids: ['fraction-whole-number-bias'],
      recommended_content_type: 'remedial_micro_module',
      status: 'completed',
      generated_content_id: 'gen-demo-step-back',
    },
    {
      phase: 'repair',
      title: 'Repair The Comparison Rule',
      target_kc_ids: ['KC-1'],
      support_level: 'medium',
      objective: 'Compare fractions by whole amount instead of separate numerator and denominator cues.',
      guidance: 'Ask the learner to justify sameness using the picture and the whole.',
      misconception_ids: ['fraction-whole-number-bias'],
      recommended_content_type: 'worked_example',
      status: 'in_progress',
      generated_content_id: 'gen-demo-worked-example',
    },
    {
      phase: 'return',
      title: 'Return To Target',
      target_kc_ids: ['KC-2'],
      support_level: 'medium',
      objective: 'Reconnect the repaired understanding to the original target KC.',
      guidance: 'Bridge the repaired whole model back to the original comparison task.',
      misconception_ids: ['fraction-whole-number-bias'],
      recommended_content_type: 'practice_problem',
      status: 'pending',
      generated_content_id: null,
    },
  ],
  current_step_index: 1,
  completed_generation_ids: ['gen-demo-step-back', 'gen-demo-worked-example'],
  progression_decision: 'held',
  progression_rationale:
    'Recent linked evidence is still support-heavy, so the workflow should stay on the repair target before returning.',
  progression_target_kc_ids: ['KC-1'],
  progression_evidence_observation_count: 4,
  progression_evidence_confidence: 0.72,
  progression_average_observed_mastery: 0.68,
  progression_low_support_success_count: 1,
  summary: {
    status: 'held',
    current_phase: 'repair',
    current_step_title: 'Repair The Comparison Rule',
    current_step_target_kc_ids: ['KC-1'],
    next_phase: 'return',
    completed_step_count: 1,
    step_count: 3,
    progression_decision: 'held',
    progression_rationale:
      'Hold on the repair target until the learner shows stronger low-support evidence.',
    progression_target_kc_ids: ['KC-1'],
    progression_evidence_observation_count: 4,
    progression_evidence_confidence: 0.72,
    progression_average_observed_mastery: 0.68,
    progression_low_support_success_count: 1,
    next_step: {
      action: 'deliver',
      content_type: 'worked_example',
      target_stage: 'repair',
      target_kc_ids: ['KC-1'],
      rationale: 'Stay on the repair target and reduce support only if the learner explains the whole correctly.',
    },
    continue_action: {
      kind: 'advance_remediation',
      method: 'POST',
      endpoint: '/api/remedial/sessions/rem-demo-1/advance',
      resource_id: 'rem-demo-1',
      generation_id: 'gen-demo-worked-example',
      learning_session_id: 'session-fractions-bridge',
      content_type: 'worked_example',
      target_stage: 'repair',
      target_kc_ids: ['KC-1'],
      request_payload: {
        learner_prompt: 'Advance only if the learner explains the whole correctly without relying on numerator-only cues.',
        curriculum_context: ['Equivalent fractions'],
      },
      rationale: 'Resume the current remediation repair step.',
    },
  },
  created_at: '2026-03-16T08:35:00Z',
  updated_at: '2026-03-16T08:53:00Z',
}

export const demoLearnerWorkspace: LearnerWorkspace = {
  student_id: SAMPLE_STUDENT_ID,
  summary: demoProfileSummary,
  active_artifact: {
    kind: 'generated_content',
    resource_id: 'gen-demo-worked-example',
    generation_id: 'gen-demo-worked-example',
    learning_session_id: 'session-fractions-bridge',
    flow_type: 'lesson',
    status: 'ready_for_next_step',
    current_phase: 'consolidate',
    content_type: 'worked_example',
    rationale: 'The generated content artifact is the latest learner-facing asset in the active lesson flow.',
  },
  continue_action: practiceContinueAction,
  affective_support: {
    kind: 'encouragement',
    title: "You're on a roll!",
    detail: 'Keep going — your focus is paying off.',
  },
  generated_content: demoGeneration,
  remediation_session: demoRemediationSession,
  socratic_session: demoSocraticSession,
}

export const demoGenerationHistory: LearnerGenerationHistoryEntry[] = [
  {
    generation_id: 'gen-demo-worked-example',
    learning_session_id: 'session-fractions-bridge',
    source_generation_id: null,
    content_type: 'worked_example',
    flow_type: 'lesson',
    status: 'delivered',
    delivered_phase: 'consolidate',
    progression_action: 'attempt_transfer',
    target_stage: 'transfer',
    active_target_kc_ids: ['KC-1'],
    intervention_type: 'targeted_practice',
    rationale: 'Generated a final bridge example before the learner moves into transfer practice.',
    next_step: demoGeneration.workflow_summary?.next_step ?? demoProfileSummary.current_flow.next_step,
    continue_action: practiceContinueAction,
    created_at: '2026-03-16T08:50:00Z',
  },
  {
    generation_id: 'gen-demo-step-back',
    learning_session_id: 'session-fractions-bridge',
    source_generation_id: null,
    content_type: 'remedial_micro_module',
    flow_type: 'remediation',
    status: 'delivered',
    delivered_phase: 'step_back',
    progression_action: 'rebuild_prerequisite_first',
    target_stage: 'repair',
    active_target_kc_ids: ['KC-1'],
    intervention_type: 'step_back',
    rationale: 'Started remediation by rebuilding the prerequisite whole-model concept.',
    next_step: {
      action: 'deliver',
      content_type: 'worked_example',
      target_stage: 'repair',
      target_kc_ids: ['KC-1'],
      rationale: 'Follow the step-back module with a repair worked example.',
    },
    continue_action: {
      kind: 'generate_follow_up',
      method: 'POST',
      endpoint: '/api/content/generate',
      resource_id: 'gen-demo-step-back',
      generation_id: 'gen-demo-step-back',
      learning_session_id: 'session-fractions-bridge',
      content_type: 'remedial_micro_module',
      target_stage: 'repair',
      target_kc_ids: ['KC-1'],
      request_payload: {
        student_id: SAMPLE_STUDENT_ID,
        learning_session_id: 'session-fractions-bridge',
        source_generation_id: 'gen-demo-step-back',
        target_kc_ids: ['KC-1'],
        target_lo_ids: ['LO-1'],
        requested_content_type: 'worked_example',
        intent: 'explanation',
        curriculum_context: ['Equivalent fractions'],
      },
      rationale: 'Re-open the prerequisite repair artifact.',
    },
    created_at: '2026-03-16T08:38:00Z',
  },
]

export const demoSocraticHistory: LearnerSocraticSessionHistoryEntry[] = [
  {
    session_id: 'soc-demo-1',
    learning_session_id: 'session-fractions-bridge',
    target_kc_ids: ['KC-1'],
    target_lo_ids: ['LO-1'],
    status: 'ready_for_follow_up',
    turn_count: 2,
    latest_prompt_style: 'transfer_check',
    latest_steering_action: 'verify_transfer',
    latest_next_action: 'advance',
    latest_evidence_strength: 'demonstrated',
    rationale: 'The latest Socratic turn shows conceptual understanding strong enough for transfer practice.',
    next_step: demoSocraticResponse.summary.next_step,
    continue_action: {
      kind: 'generate_follow_up',
      method: 'POST',
      endpoint: '/api/content/generate',
      resource_id: 'soc-demo-1',
      generation_id: 'soc-gen-demo-1',
      learning_session_id: 'session-fractions-bridge',
      content_type: 'practice_problem',
      target_stage: 'transfer',
      target_kc_ids: ['KC-1'],
      request_payload: {
        student_id: SAMPLE_STUDENT_ID,
        learning_session_id: 'session-fractions-bridge',
        source_generation_id: 'soc-gen-demo-1',
        target_kc_ids: ['KC-1'],
        target_lo_ids: ['LO-1'],
        requested_content_type: 'practice_problem',
        intent: 'practice',
        curriculum_context: ['Equivalent fractions'],
      },
      rationale: 'Resume the active Socratic session or inspect the latest turn.',
    },
    created_at: '2026-03-16T08:49:00Z',
    updated_at: '2026-03-16T08:52:00Z',
  },
]

export const demoRemediationHistory: LearnerRemediationSessionHistoryEntry[] = [
  {
    session_id: 'rem-demo-1',
    target_kc_id: 'KC-2',
    focus_kc_ids: ['KC-1', 'KC-2'],
    prerequisite_kc_ids: ['KC-1'],
    latest_generation_id: 'gen-demo-worked-example',
    status: 'held',
    current_phase: 'repair',
    completed_step_count: 1,
    step_count: 3,
    progression_decision: 'held',
    progression_rationale: 'The learner still needs stronger low-support repair evidence before returning to the original target.',
    next_step: demoRemediationSession.summary.next_step,
    continue_action: demoRemediationSession.summary.continue_action,
    created_at: '2026-03-16T08:35:00Z',
    updated_at: '2026-03-16T08:53:00Z',
  },
]

export const demoTeacherInterventionAction: TeacherInterventionActionContract = {
  action_key: 'teacher-action-session-fractions-bridge',
  proposal_status: 'available',
  flow_type: 'lesson',
  learning_session_id: 'session-fractions-bridge',
  remediation_session_id: 'rem-demo-1',
  socratic_session_id: 'soc-demo-1',
  progression_action: 'attempt_transfer',
  target_stage: 'transfer',
  active_target_kc_ids: ['KC-1'],
  current_phase: 'consolidate',
  rationale:
    'The learner appears transfer-ready, but the teacher can approve the recommendation, defer it, or redirect to a different backend-owned option based on classroom context.',
  source: 'teacher_intervention_policy',
  next_step: demoProfileSummary.current_flow.next_step,
  proposed_action: practiceContinueAction,
  available_options: [
    {
      option_id: 'recommended',
      label: 'Send transfer practice',
      rationale: 'Keep momentum and test learner-owned transfer on the original target KC.',
      is_recommended: true,
      continue_action: practiceContinueAction,
    },
    {
      option_id: 'worked_example_support_reset',
      label: 'Hold with one more worked example',
      rationale: 'Add one more modeled bridge if classroom observation suggests the learner is still brittle.',
      is_recommended: false,
      continue_action: {
        kind: 'generate_follow_up',
        method: 'POST',
        endpoint: '/api/content/generate',
        resource_id: null,
        generation_id: null,
        learning_session_id: 'session-fractions-bridge',
        content_type: 'worked_example',
        target_stage: 'repair',
        target_kc_ids: ['KC-1'],
        request_payload: {
          student_id: SAMPLE_STUDENT_ID,
          learning_session_id: 'session-fractions-bridge',
          target_kc_ids: ['KC-1'],
          target_lo_ids: ['LO-1'],
          intent: 'practice',
          requested_content_type: 'worked_example',
          curriculum_context: ['Equivalent fractions'],
        },
        rationale: 'Generate one more teacher-approved worked example before transfer.',
      },
    },
    {
      option_id: 'continue_remediation',
      label: 'Return to remediation',
      rationale: 'Reopen the remediation arc if the learner is still relying on numerator-denominator heuristics.',
      is_recommended: false,
      continue_action: demoRemediationSession.summary.continue_action,
    },
  ],
  allowed_decisions: ['approve', 'select_option', 'defer', 'escalate_human'],
  latest_decision: {
    action_key: 'teacher-action-session-fractions-bridge',
    decision_id: 'teacher-decision-demo-1',
    decision: 'select_option',
    status: 'option_selected',
    selected_option_id: 'worked_example_support_reset',
    note: 'Observed hesitation when the visual scaffold was removed.',
    decided_by: 'Ms. Rivera',
    decided_role: 'teacher',
    decided_at: '2026-03-16T09:02:00Z',
    execution_action: {
      kind: 'generate_follow_up',
      method: 'POST',
      endpoint: '/api/content/generate',
      resource_id: null,
      generation_id: null,
      learning_session_id: 'session-fractions-bridge',
      content_type: 'worked_example',
      target_stage: 'repair',
      target_kc_ids: ['KC-1'],
      request_payload: {
        requested_content_type: 'worked_example',
      },
      rationale: 'Teacher requested one more bridge example before transfer.',
    },
  },
  updated_at: '2026-03-16T09:02:00Z',
}

const blockedLearnerCard: TeacherLearnerCard = {
  student_id: '22222222-2222-2222-2222-222222222222',
  grade_level: '5',
  engagement: 'medium',
  frustration: 'medium',
  current_flow: {
    status: 'idle',
    flow_type: 'idle',
    learning_session_id: null,
    remediation_session_id: null,
    socratic_session_id: null,
    current_phase: 'idle',
    current_content_type: null,
    last_generation_id: null,
    progression_action: 'monitor',
    target_stage: 'target',
    active_target_kc_ids: [],
    deferred_target_kc_ids: [],
    transfer_target_kc_ids: [],
    session_phase: 'monitor',
    session_arc_action: 'steady',
    session_stuck_loop_risk: 'low',
    rationale: 'No active workflow is running for this learner.',
    progression_source: 'insufficient',
    next_step_source: 'insufficient',
    next_step: {
      action: 'monitor',
      content_type: null,
      target_stage: 'target',
      target_kc_ids: [],
      rationale: 'Wait for prerequisite mastery before starting the next curriculum resource.',
    },
    continue_action: {
      kind: 'idle',
      method: null,
      endpoint: null,
      resource_id: null,
      generation_id: null,
      learning_session_id: null,
      content_type: null,
      target_stage: 'target',
      target_kc_ids: [],
      request_payload: {},
      rationale: 'No continue action is available yet.',
    },
    updated_at: '2026-03-16T08:56:00Z',
  },
  curriculum_progression: {
    status: 'blocked_on_prerequisites',
    source: 'knowledge_state_and_flow',
    flow_type: 'idle',
    current_stage: 'target',
    progression_action: 'monitor',
    active_target_kc_ids: [],
    resource_count: 2,
    mastered_resource_count: 0,
    ready_resource_count: 0,
    blocked_resource_count: 1,
    active_resource_count: 0,
    mastered_resource_ratio: 0,
    current_resource: null,
    next_resource: null,
    blocked_resources: [
      {
        resource_id: 'CURR-2',
        title: 'Equivalent Fraction Practice',
        state: 'blocked',
        learning_objective_ids: ['LO-1'],
        knowledge_component_ids: ['KC-2'],
        blocked_prerequisite_kc_ids: ['KC-1'],
        mastery_ratio: 0.12,
        current_flow_aligned: false,
        target_stage: 'target',
        rationale: 'The learner still needs the prerequisite equivalence concept before this resource is ready.',
      },
    ],
    ready_resources: [],
    rationale: 'Curriculum progression is blocked until the learner rebuilds the prerequisite KC.',
    updated_at: '2026-03-16T08:56:00Z',
  },
  recent_activity: {
    generation_count: 1,
    observation_count: 4,
    socratic_assessment_count: 0,
    last_learning_session_id: null,
    last_generation_id: null,
    last_event_at: '2026-03-16T08:40:00Z',
  },
  intervention: {
    action_key: 'idle',
    proposal_status: 'unavailable',
    recommended_action_kind: 'idle',
    option_count: 0,
    latest_decision_status: null,
  },
  display_rationale: 'Blocked on prerequisite: Fraction model reading (KC-1 mastery 0.42).',
  attention_level: 'medium',
  triage_section: 'needs_attention',
  attention_reasons: ['blocked_on_prerequisites'],
}

export const demoTeacherClassroom: TeacherClassroomReadModel = {
  classroom_id: 'CLASS-1',
  title: 'Grade 5 Fractions',
  teacher_label: 'Ms. Rivera',
  grade_level: '5',
  subject: 'math',
  learner_count: 2,
  active_flow_count: 1,
  intervention_available_count: 1,
  blocked_progression_count: 1,
  attention_needed_count: 2,
  missing_learner_count: 1,
  updated_at: '2026-03-16T09:05:00Z',
  missing_student_ids: ['missing-student-id'],
  learners: [
    {
      student_id: SAMPLE_STUDENT_ID,
      grade_level: demoProfileSummary.grade_level,
      engagement: demoProfileSummary.engagement,
      frustration: demoProfileSummary.frustration,
      current_flow: demoProfileSummary.current_flow,
      curriculum_progression: demoProfileSummary.curriculum_progression,
      recent_activity: demoProfileSummary.recent_activity,
      intervention: {
        action_key: demoTeacherInterventionAction.action_key,
        proposal_status: 'available',
        recommended_action_kind: demoTeacherInterventionAction.proposed_action.kind,
        option_count: demoTeacherInterventionAction.available_options.length,
        latest_decision_status: demoTeacherInterventionAction.latest_decision?.status ?? null,
      },
      display_rationale: 'Intervention available: backend recommends guided bridge practice on equivalent fractions.',
      attention_level: 'medium',
      triage_section: 'teacher_action',
      attention_reasons: ['teacher_intervention_available'],
    },
    blockedLearnerCard,
  ],
}

export const demoTeacherClassrooms: TeacherClassroomOverview[] = [
  {
    classroom_id: demoTeacherClassroom.classroom_id,
    title: demoTeacherClassroom.title,
    teacher_label: demoTeacherClassroom.teacher_label,
    grade_level: demoTeacherClassroom.grade_level,
    subject: demoTeacherClassroom.subject,
    learner_count: demoTeacherClassroom.learner_count,
    active_flow_count: demoTeacherClassroom.active_flow_count,
    intervention_available_count: demoTeacherClassroom.intervention_available_count,
    blocked_progression_count: demoTeacherClassroom.blocked_progression_count,
    attention_needed_count: demoTeacherClassroom.attention_needed_count,
    missing_learner_count: demoTeacherClassroom.missing_learner_count,
    updated_at: demoTeacherClassroom.updated_at,
  },
]

export const teacherContractGaps: TeacherContractGap[] = [
  {
    severity: 'P2',
    title: 'Course progression is local, not course-planner-owned',
    why_it_matters:
      'The backend owns local progression through curriculum_progression and current_flow, but there is no true course-level planner with cross-unit sequencing authority.',
    current_backend:
      'Backend exposes learner curriculum progression, classroom posture, and dependency-aware resource ranking. A fuller course planner is deferred until product needs exceed this.',
    frontend_response:
      'Treat `current_flow` and `curriculum_progression` as authoritative. Avoid inventing cross-unit sequencing logic in the frontend.',
  },
  {
    severity: 'P2',
    title: 'No multimodal artifact contract yet',
    why_it_matters:
      'The revised spec includes diagrams and richer media, but the current generation contract is still text-block oriented.',
    current_backend:
      'Generated content exposes a discriminated `response.artifacts` contract with a stable `text` variant. Diagram, simulation, and interactive variants are future extensions.',
    frontend_response:
      'Design blocks as extensible cards and reserve space for future visual artifacts without pretending the data exists today.',
  },
  {
    severity: 'P2',
    title: 'Teacher analytics are summary-oriented, not dashboard-grade',
    why_it_matters:
      'Teachers see classroom cards, learner summaries, and intervention rationale but do not yet have trend lines, standards mastery views, or richer historical analytics.',
    current_backend:
      'Teacher-safe data flows through summary read models, rationale fields, classroom contracts, and intervention proposals. Richer analytics are deferred until product needs justify them.',
    frontend_response:
      'Use summary read models and rationale fields as the teacher UI source of truth. Keep raw telemetry as a developer/admin tool only.',
  },
]
